- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'app-frontend'
  static_configs:
  - targets: ['fe-frontend.app-frontend:8080']

- job_name: 'app-backend'
  static_configs:
  - targets: ['localhost:8888']

- job_name: 'postgresql'
  static_configs:
  - targets: ['db-postgresql.app-backend:5432']

- job_name: 'blackbox-metrics'
  static_configs:
  - targets: ['blackbox-prometheus-blackbox-exporter.monitoring:9115']