- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'app-backend'
  static_configs:
  - targets: ['backend.app-backend:8888']

- job_name: 'postgresql'
  static_configs:
  - targets: ['app-postgresql-metrics.db-app:9187']

- job_name: 'blackbox-metrics'
  static_configs:
  - targets: ['prometheus-blackbox-exporter.monitoring:9115']