apiVersion: v2
appVersion: v0.99
description: A Helm chart for Karma - an UI for Prometheus Alertmanager
home: https://github.com/prymitive/karma
kubeVersion: '>= 1.19-0'
maintainers:
- email: cdesaintmartin@wiremind.io
  name: desaintmartin
- email: amrini@wiremind.io
  name: machine424
- email: fminaud@wiremind.io
  name: francoisminaud
name: karma
sources:
- https://github.com/wiremind/wiremind-helm-charts/tree/main/charts/karma
- https://github.com/prymitive/karma
type: application
version: 2.1.0
