env:
- name: ALERTMANAGER_URI
  value: http://monitoring-prometheus-alertmanager

ingress:
  enabled: true
  hosts:
  - chart-example.local
  path: /
  pathType: ImplementationSpecific

kthxbyeSidecar:
  enabled: true
  alertmanagerServiceName: prometheus-alertmanager
  alertmanagerServicePort: 80
